# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and test
on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mesa-utils xvfb x11-xserver-utils

      - name: Checkout mod repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK version
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          validate-wrappers: true

      - name: Download DragonRealmCore
        run: curl -L -o 'libs/DragonRealmCore 1.7.10 V33a.jar' 'https://dragonrealm.overminddl1.com/downloads/ReikaMods/DragonRealmCore%201.7.10%20V33a.jar'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup the workspace
        run: ./gradlew --build-cache --info --stacktrace setupCIWorkspace

      - name: Compile the mod
        run: ./gradlew --build-cache --info --stacktrace assemble

      - name: Attach compilation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}-build-libs
          path: build/libs/
          retention-days: 90

      - name: Run post-build checks
        id: build_mod
        run: xvfb-run --server-args="-screen 0 1366x768x24" ./gradlew --build-cache --info --stacktrace build
